let shopItemsData = [
    {
      id: "jfhgbvnscs",
      name: "Erphone Wireless",
      price: 160,
      desc: "Earphone wireless adalah earphone yang sangat berguna untuk orang-orang yang tidak menyukai keribetan dengan adanya kabel. Earphone kekinian yang tentunya tidak ketinggalan jaman. Pastinya kekinian.",
      img: "images/img-1.jpg",
    },
    {
      id: "ioytrhndcv",
      name: "Keyboard",
      price: 100,
      desc: "Keyboard external adalah keyboard yang sangat membantu para pekerja, gamer maupun pengguna laptop lainnya. Jika keyboard internal rusak, maka pengguna laptop bisa menggunakan keyboard external ini.",
      img: "images/img-2.jpg",
    },
    {
      id: "wuefbncxbsn",
      name: "Camera Canon",
      price: 900,
      desc: "Kamera Canon merupakan salah satu kamera terbaik. baik untuk pemula maupun profesional. Warna hitam yang elegant membuat kamera ini menjadi lebih terlihat mahal dan sangat classic. Jepretan yang indah.",
      img: "images/img-3.jpg",
    },
    {
      id: "thyfhcbcv",
      name: "Black Mouse",
      price: 300,
      desc: "Mouse sangat berguna bagi kaum modern yang selalu menggunakan komputer/laptop untuk beraktifitas. Mouse yang satu ini, memiliki warna yang sangat elegant yang membuatnya menjadi terlihat mahal.",
      img: "images/img-4.jpg",
    },
    {
      id: "thiecbawdjksadjk",
      name: "Black Headphone",
      price: 150,
      desc: "Headphone tanpa kabel, sangat cocok digunakan untuk olahraga maupun berpergian menggunakan kendaraan umum jika bosan. Karena tidak ada kabel yang melilit sehingga sangat memudahkan penggunnanya untuk aktivitasnya.",
      img: "images/img-5.jpg",
    },
    {
      id: "iuertrywebncdjksadjk",
      name: "Canon Camera",
      price: 950,
      desc: "Kamera canon dengan segala kecanggihannya, membuat hasil jepretan milik anda menjadi lebih profesional lagi Ditambah design dari kamera yang sangat indah dan membuat anda terlihat seperti profesional, indah dan berkelas.",
      img: "images/img-6.jpg",
    },
    {
      id: "thierytbvcbvzdhadjk",
      name: "Black Mouse",
      price: 250,
      desc: "Mouse dengan warna blue menyala membuat penggunanya terkesan jago dan mahir mengoperasikan komputer.Mouse sangat berguna unntuk aktivitas perkantoran serta pembelajaran yang diadakan. Apalgi mouse ini desaignnya elegant.",
      img: "images/img-7.jpg",
    },
    {
      id: "trfoiwfcnbcawdjksadjk",
      name: "Earphone Cable",
      price: 150,
      desc: "Earphone kabel memang sudah ketinggalan jaman. Namun tidak untuk earphone yang satu ini, karena earphone ini didesain dengan sangat elegant dan sangat minimalis. Sehingga terlihat seperti earphone modern yang kekinian dan indah, saat dikenakan.",
      img: "images/img-8.jpg",
    },
    {
      id: "cbvxbcvsceldk",
      name: "Nikon Camera",
      price: 850,
      desc: "Nikon kamera adalah kamera yag dikeluarkan oleh Nikon. Desain hitam dari kamera Nikon ini membuat pemakainya terlihat seperti profesinal. Kamera ini juga sudah dilengakapi oleh teknologi yang canggih. Membuat jepretan anda menjadi profesional.",
      img: "images/img-9.jpg",
    },
    {
      id: "oiopijmjkhuihb",
      name: "White keyboard",
      price: 120,
      desc: "Keyboard putih ini sangat indah, sangat cantik dan sangat cocok untuk manusia jaman sekarang yang bekerja di depan komputer/laptop. Warna putih yang menandakan kesucian dan keindahan yang dimiliki oleh keyboard ini sangat memanjakan mata.",
      img: "images/img-10.jpg",
    },
    {
      id: "oiopijewyiohbjhib",
      name: "Black Earphone",
      price: 355,
      desc: "Black headphone tanpa kabel ini adalah salah satu produk unggulan di toko ini. Karena wireless yang menarik pembeli, sehingga pembeli tidak keribetan dengan kabel yang ada. Dan juga, warna hitam pekat membuat hati terpikat, sangat mempesona.",
      img: "images/img-11.png",
    },
    {
      id: "rtytytuyuytyytbvncv",
      name: "Black Mouse",
      price: 350,
      desc: "Black mouse adalah mouse yang sangat indah untuk dimiliki. Mouse ini sangat enak untuk digenggam, dan tidak memiliki kabel/wireless, sangat membuat penggunanya tidak ribet dengan panjangnya kabel dan lilitan kabel yang membuat pusing dan tidak estetik.",
      img: "images/img-12.png",
    },
  ];
  